# Generated by Django 3.0.8 on 2021-06-29 23:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selections',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('notes', models.CharField(max_length=500)),
                ('selections_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menu.Options')),
            ],
        ),
    ]
