# Generated by Django 3.0.8 on 2021-06-30 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_selections'),
    ]

    operations = [
        migrations.RenameField(
            model_name='options',
            old_name='menu_id',
            new_name='menu',
        ),
    ]
