# Generated by Django 3.0.8 on 2021-07-02 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20210630_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selections',
            old_name='selections_id',
            new_name='option',
        ),
    ]
